method: P2RNet
resume: False
finetune: False
weight: []
seed: 42
device:
  use_gpu: True
  gpu_ids: '0,1,2,3'
  num_workers: 12
  world_size: 1 # will be overloaded by distributed setting
  dist_url: env://
data:
  dataset: virtualhome
  split: datasets/virtualhome_22_classes/splits/script_level
  num_frames: 768
  num_seeds: 512
  seed_sampling: uniform
  max_gt_boxes: 10
  num_target: 128
  vote_factor: 1
  cluster_sampling: vote_fps
  no_height: True
  num_gaussian: 100
model:
  backbone:
    method: STGCN
    loss: Null
  centervoting:
    method: CenterVoteModule
    loss: Null
  detection:
    method: ProposalNet
    loss: BoxNetDetectionLoss
optimizer:
  method: Adam
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0
  clip_norm: -1
scheduler:
  milestones: [80, 120, 160]
  gamma: 0.1
train:
  epochs: 180
  phase: 'full'
  freeze: []
  batch_size: 8
val:
  phase: 'full'
  batch_size: 8
demo:
  phase: 'full'
log:
  vis_path: visualization
  save_weight_step: 50
  save_results: True
  vis_step: 10
  print_step: 10
  path: out/p2rnet
